apiVersion: v1
kind: Secret
metadata:
  name: chat-secret
  namespace: chat-app
type: Opaque
data:
  MONGO_USER: YWRtaW4=  # base64 encoded "admin"
  MONGO_PASS: cGFzc3dvcmQ=  # base64 encoded "password"