apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: chat-app
spec:
  selector:
    app: prometheus
  ports:
  - port: 9090
    targetPort: 9090
  type: LoadBalancer